### ISSUE TITLE
polaris controller not working with when installing

### ISSUE THREAD

**Issue by karl-chanel** [polarismesh/polaris-controller#117]

**Comment by zhangqian1992** [comment]
> > wsl , polaris 跑在华为云上
> 
> 可以执行 bash -x install.sh 看下是哪一步出现问题导致无法 replace 镜像地址

Ubuntu20.04LTS 执行 install.sh 出现replaceVar: command not found。所以yaml的变量都没有替换成功，无法启动

**Comment by zhangqian1992** [comment]
> 在polaris controller 的安装过程中按照文档配置好token和host后，运行install.sh没有把sidecar envoy controller的版本注入到inject.yaml configmap.yaml controller.yaml中导致controller启动失败需要手动把各种image的版本信息配置到上述几个yaml中，我看了下install.sh应该是replace函数有问题，没有成功替换掉配置的镜像版本信你

> 在polaris controller 的安装过程中按照文档配置好token和host后，运行install.sh没有把sidecar envoy controller的版本注入到inject.yaml configmap.yaml controller.yaml中导致controller启动失败需要手动把各种image的版本信息配置到上述几个yaml中，我看了下install.sh应该是replace函数有问题，没有成功替换掉配置的镜像版本信息

你这个函数的问题解决了吗？
