### ISSUE TITLE
是否考虑跨namespace同步

### ISSUE THREAD

**Issue by forrestlinfeng** [polarismesh/polaris-controller#149]
k8s的namespace不支持大写，有一些北极星名字创建的时候就包含大写的Namespace，如果能支持跨namespace就比较好

**Comment by chuntaojun** [comment]
是指希望 k8s namespace => 映射到 polaris namespace 这种吗？

**Comment by forrestlinfeng** [comment]
是的

liaochuntao ***@***.***> 于2023年12月9日周六 22:28写道：

**Comment by forrestlinfeng** [comment]
现在貌似是写死的映射方式，希望支持在yaml支持指定目的polaris namespace，这样就能避免一一对应

**Comment by forrestlinfeng** [comment]
已提PR
