### ISSUE TITLE
bug: The old instances is not removed when pod deleted

### ISSUE THREAD

**Issue by wayne-cheng** [polarismesh/polaris-controller#5]
If you deployed the pod by the resouce `delpoyment` in your K8S cluster, when the pod is deleted and running again automaticlly, the service endpoints will change and polaris-controller will add the new endpoint to the instance, but the old instance is not removed in fact.

**Comment by zhangzerui20** [comment]
The polaris-server stand-alone version has a data inconsistency problem, which has been fixed in release-1.4.0. Please use the following release to update.

https://github.com/polarismesh/polaris/releases/tag/v1.4.0
