### ISSUE TITLE
当 polaris-sidecar 被重新注入时，对应的相关资源都应该被重新update过

### ISSUE THREAD

**Issue by chuntaojun** [polarismesh/polaris-controller#54]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Environment**
- Version: [e.g. v1.0.0]
- OS: [e.g. CentOS8]

**Additional context**

**Comment by lhiamgeek** [comment]
will give it a try

**Comment by lhiamgeek** [comment]
This issue can be solved by the following approach:
1. generate the content of polaris.yaml and insert into the environment params of pod
2. while creating the pod, generate polaris.yaml based on the environment params set at the first step.

by this method, the original configMap can be removed from the pod
