### ISSUE TITLE
语义歧义问题

### ISSUE THREAD

**Issue by mlboy** [polarismesh/polaris-controller#6]
看文档描述是 true 的时候 不自动注册，但和标签语义有点相反，最好可以统一。要不容易迷惑
polaris.cloud.tencentyun.com/autoRegister="true"

**Comment by zhangzerui20** [comment]
@mlboy 这里语义确实有歧义，我们调整了一次注解的 key ，现在改成了 `polarismesh.cn/enableRegister` ，false 表示关闭同步功能。
