### ISSUE TITLE
polaris-server暴力停机并重启后polaris-controller无法恢复数据同步

### ISSUE THREAD

**Issue by MI-cool** [polarismesh/polaris-controller#65]
**What is the feature you want to add?**
polaris-controller需要增强一下容错恢复能力

**Additional context**
测试时polaris-server是采用的standalone单机模式部署，采用server节点ip配置，在k8s集群内安装polaris-controller后观测到服务数据已同步到polaris-server。

kill -9 polaris-server进程，然后重启polaris-server，观察发现服务数据无法再次同步到polaris-server

**Comment by chuntaojun** [comment]
ok，我们这里跟进处理下

**Comment by chuntaojun** [comment]
@lhiamgeek

**Comment by lhiamgeek** [comment]
I will give it a try
